src/Entity/Projets.php
<?php

namespace App\Entity;

use App\Repository\ProjetsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProjetsRepository::class)]
class Projets
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Titre;

    #[ORM\Column(type: 'string', length: 255)]
    private $Description;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $image1;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $img2;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Repo;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $Site;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage1(): ?string
    {
        return $this->image1;
    }

    public function setImage1(?string $image1): self
    {
        $this->image1 = $image1;

        return $this;
    }

    public function getImg2(): ?string
    {
        return $this->img2;
    }

    public function setImg2(?string $img2): self
    {
        $this->img2 = $img2;

        return $this;
    }

    public function getRepo(): ?string
    {
        return $this->Repo;
    }

    public function setRepo(?string $Repo): self
    {
        $this->Repo = $Repo;

        return $this;
    }

    public function getSite(): ?string
    {
        return $this->Site;
    }

    public function setSite(?string $Site): self
    {
        $this->Site = $Site;

        return $this;
    }
}

src/Form/AddProjetType.php
<?php

namespace App\Form;

use App\Entity\Projets;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AddProjetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Titre')
            ->add('Description')
            ->add('image1')
            ->add('img2')
            ->add('Repo')
            ->add('Site')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Projets::class,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
}

src/Controller/ProjController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Projets;
use App\Form\AddProjetType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Persistence\ManagerRegistry;

class ProjController extends AbstractController
{
    #[Route('/admin', name: 'admin')]
    public function index(Request $request, EntityManagerInterface $entityManager): Response
    {
        $projet = new Projets();
        // ...

        $form = $this->createForm(AddProjetType::class, $projet,[
        ]);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $entityManager->persist($projet);
            $entityManager->flush();
        }
        return $this->renderForm('proj/index.html.twig', [
            'form' => $form,
        ]);
    }
}

src/Controller/ProjetsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use App\Entity\Projets;
use Symfony\Component\Form\FormBuilderInterface;

class ProjetsController extends AbstractController
{
    #[Route('/projets', name: 'projets')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $repository = $doctrine->getRepository(Projets::class)->findAll();
        $projets = $repository;
        return $this->render('projets/index.html.twig', [
            'controller_name' => 'ProjetsController',
            'projets' => $projets
        ]);
    }
   
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('projets') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('projets') }}
        {% endblock %}
    </head>
    <body>
    <ul style="list-style:none">
    <navbar style="display:flex; justify-content: space-evenly;" class="navbar navbar-expand-lg navbar-light bg-light">
    <li>
    <a href="/" class="btn btn-primary">Accueil</a>
    </li>
    <li>
    <a href="/projets" class="btn btn-primary">Projets</a>
    </li>
    </ul>
    </navbar>
        {% block body %}{% endblock %}
    </body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
</style>

<div class="example-wrapper">
    <h1>Thomas PINTO-PICOT</h1>
    <p>Web Developer Pro in PHP/C++/Kotlin/Python</p>
    <p></p>
    <p>Here you will be able to see my <a href="/projets"> projects </a></p>
</div>
{% endblock %}

templates/proj/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProjController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
</style>

<div class="example-wrapper">
<h1>Pour ajouter un projet : </h1>
{{ form_start(form) }}
        {{ form_label(form.Titre) }}
        {{ form_widget(form.Titre) }}
   
        {{ form_label(form.Description) }}
        {{ form_widget(form.Description) }}
        {{ form_label(form.image1) }}
        {{ form_widget(form.image1) }}
        {{ form_rest(form) }}
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    {{ form_end(form) }}


</div>
{% endblock %}

templates/projets/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProjetsController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif;}
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<div>
<h1>Voici tous mes projets:</h1>
    {% for post in projets %}
    <div class="row row-cols-1 row-cols-md-2 g-4" style="width:50%">
  <div class="col">
    <div class="card">
    <img src="{{post.image1}}" class="card-img-top"></p>
    <div class="card-body">
        <h5 class="card-title">{{ post.Titre }}</h5>
        <p class="card-text">{{ post.Description }}</p>
         </div>
         <a href="{{post.repo}}" class="btn btn-primary">Go somewhere</a>
</div>
</div>
</div>
{% endfor %}
</div>
{% endblock %}